window.SCHOLARSHIP_ROBOT_DATA = {
  applicant: {
    name: "Graduate Scholarship Applicant",
    email: "Stored in private local profile",
    location: "Louisiana",
    mailingCityStateZip: "Stored in private local profile",
    zipCode: "",
    targetProfile: "Full-time U.S. graduate student",
    graduateGpa: 0,
    priorGpa: 0,
    educationTruth: "resume_paste_verified_transcripts_pending",
    currentDegreeForApplications: "Graduate computer science program",
    completedGraduateDegree: "Graduate engineering management degree",
    education: [
      "Computer information systems undergraduate degree",
      "Engineering management graduate degree",
      "Current computer science graduate study"
    ],
    verifiedResumeHighlights: [
      "Cross-sector data analytics and operations experience",
      "Nonprofit client-services and data coordination",
      "Student media and editorial leadership",
      "Public-sector data and technology internships",
      "Entrepreneurship and technical portfolio projects"
    ],
    verifiedSkills: [
      "Excel automation, SQL, early Power BI, dashboards, and reporting",
      "SharePoint metadata, Power Automate, Microsoft Graph API concepts, and cloud workflow design",
      "Python, Java, JavaScript, HTML, CSS, REST APIs, and early C#/.NET Core",
      "Windows Server, Active Directory, identity and permission management",
      "CRM cleanup, client intake data, GIS mapping, EHR systems, and HIPAA-aware data work"
    ],
    missingSubmissionFields: [
      "Account login/password steps for platform scholarships",
      "Applicant signature/certification steps",
      "Recommendation letters and recommender contact approvals"
    ],
    portfolioUrl: "https://kieronhaynes38-king.github.io/Kieron-s-portfolio/",
    youtubeUrl: "https://www.youtube.com/@kieroncH",
    instagram: "",
    publicInstagramOnlyIfHelpful: true,
    storyBank: [
      "Engineering management and technical leadership",
      "Computer science, AI, infrastructure, and database systems",
      "Cloud/data systems, dashboards, SQL, Power BI, SharePoint, CRM cleanup",
      "AI automation and prompt workflow design",
      "SUNO/UNO leadership, Editor-in-Chief, Majeste Productions, Freshman Class President, Beta Gamma Sigma",
      "Long-term community service and youth leadership",
      "Filmmaking: short films, The Mark of the Savior, Black NOLA Film Fest context",
      "Entrepreneurship and self-funded college progress during COVID",
      "Resilience while balancing family responsibilities, work, and education"
    ]
  },
  submissionAttempts: [],
  statuses: [
    "prospect",
    "verified",
    "drafted",
    "ready_for_review",
    "filled_pause",
    "submitted_by_user",
    "not_eligible",
    "closed",
    "monitor_next_cycle"
  ],
  opportunitySources: [
    {
      name: "CareerOneStop Scholarship Finder",
      url: "https://www.careeronestop.org/Toolkit/Training/find-scholarships.aspx",
      countLabel: "9,500+ awards",
      publishedCount: 9500,
      fit: "Official U.S. Department of Labor database; filter for graduate study, computer science, engineering, Louisiana, service, and creative work."
    },
    {
      name: "Scholarships360 Graduate Directory",
      url: "https://scholarships360.org/scholarships/top-scholarships-for-graduate-students/",
      countLabel: "100+ graduate",
      publishedCount: 100,
      fit: "Current graduate-level applications with deadlines, award amounts, and direct apply paths."
    },
    {
      name: "Scholarships360 Computer Science Directory",
      url: "https://scholarships360.org/scholarships/computer-science-scholarships/",
      countLabel: "194 CS matches",
      publishedCount: 194,
      fit: "Computer science, cybersecurity, data, software, and technology awards."
    },
    {
      name: "Scholarship America Open Programs",
      url: "https://scholarshipamerica.org/students/browse-scholarships/",
      countLabel: "National programs",
      publishedCount: 0,
      fit: "Sponsor-administered scholarships with verified program pages and structured applications."
    },
    {
      name: "UNCF Scholarship Portal",
      url: "https://uncf.org/scholarships",
      countLabel: "HBCU and STEM",
      publishedCount: 0,
      fit: "Use graduate, STEM, Louisiana, HBCU alumni, leadership, and community-service filters after confirming sensitive eligibility."
    },
    {
      name: "TMCF Scholarship Portal",
      url: "https://www.tmcf.org/students-alumni/scholarships/",
      countLabel: "HBCU programs",
      publishedCount: 0,
      fit: "Scholarships and fellowships connected to publicly supported HBCUs, technology, leadership, and alumni pathways."
    },
    {
      name: "College Board BigFuture Search",
      url: "https://bigfuture.collegeboard.org/scholarship-search",
      countLabel: "National search",
      publishedCount: 0,
      fit: "Broad discovery lane for current deadlines; verify graduate eligibility on each sponsor page."
    },
    {
      name: "New Orleans Film Society Opportunities",
      url: "https://neworleansfilmsociety.org/",
      countLabel: "Local creative",
      publishedCount: 0,
      fit: "New Orleans filmmaker grants, labs, festival programs, and artist opportunities tied to Kieron's film portfolio."
    }
  ],
  scholarships: [
    {
      id: "asem-grad",
      name: "ASEM Undergraduate and Graduate Student Scholarships",
      sponsor: "American Society for Engineering Management",
      category: "Engineering Management",
      url: "https://asem.org/ASEM-Scholarships",
      applicationMethod: "email",
      contactEmail: "scholarship@asem.org",
      amount: "$500",
      deadline: "2026-07-15",
      status: "verified",
      verifiedOn: "2026-06-03",
      eligibility: "Graduate Engineering Management or related field, ASEM membership, full-time enrollment, 3.5+ graduate GPA, expected graduation in 2027, transcript, essay, and professor recommendation.",
      materials: "Application form, personal essay, transcript, professor recommendation, faculty confirmation of expected graduation.",
      aiPolicy: "unknown",
      sensitiveTags: [],
      matchScore: 98,
      matchReasons: ["Direct Engineering Management fit", "Graduate GPA clears 3.5", "Leadership and service matter", "Expected 2027 degree timeline may fit after verification"],
      risks: ["Requires ASEM membership", "Email-only submission", "Degree timeline must be reconciled before applying"],
      nextAction: "Verify ASEM membership and expected graduation date, then draft email packet."
    },
    {
      id: "uno-engineering",
      name: "UNO College of Engineering Scholarships",
      sponsor: "University of New Orleans College of Engineering",
      category: "UNO/Internal",
      url: "https://www.uno.edu/academics/coe/scholarships",
      applicationMethod: "internal",
      contactEmail: "",
      amount: "Varies",
      deadline: "departmental",
      status: "verified",
      verifiedOn: "2026-06-03",
      eligibility: "UNO College of Engineering undergraduate or graduate students; many awards require 3.0+ GPA, full-time enrollment, leadership, good character, and department/faculty acknowledgement.",
      materials: "Resume, transcript, faculty contact, department scholarship inquiry, FAFSA if applicable.",
      aiPolicy: "unknown",
      sensitiveTags: ["financial_need_possible"],
      matchScore: 96,
      matchReasons: ["UNO enrollment likely", "Graduate engineering/management fit", "Leadership and academic profile fit"],
      risks: ["Some awards are major-specific", "May require faculty nomination or internal process"],
      nextAction: "Contact UNO College of Engineering and department advisor with verified transcript and resume."
    },
    {
      id: "uno-grad-awards",
      name: "UNO Graduate School Awards",
      sponsor: "University of New Orleans Graduate School",
      category: "UNO/Internal",
      url: "https://www.uno.edu/academics/grad/graduate-financing/awards",
      applicationMethod: "internal",
      contactEmail: "",
      amount: "Varies",
      deadline: "departmental",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "UNO graduate applicants and students; awards are often competitive and may be coordinated through graduate departments.",
      materials: "Department inquiry, resume, transcript, statement of purpose, faculty nomination if needed.",
      aiPolicy: "unknown",
      sensitiveTags: [],
      matchScore: 92,
      matchReasons: ["Current graduate profile", "Internal awards often have fewer applicants", "Strong leadership and GPA"],
      risks: ["Nomination process may be closed", "Eligibility depends on current program"],
      nextAction: "Ask Graduate School and department for current 2026-2027 award availability."
    },
    {
      id: "nsbe",
      name: "NSBE Scholarships",
      sponsor: "National Society of Black Engineers",
      category: "Black STEM / Professional Society",
      url: "https://nsbe.org/scholarships/",
      applicationMethod: "portal",
      contactEmail: "scholarships@nsbe.org",
      amount: "Varies",
      deadline: "cycle opens soon",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "NSBE collegiate/graduate members; GPA verification required each semester. Spring/Summer GPA verification window runs April 1 to July 31, 2026.",
      materials: "MyNSBE profile, GPA verification, resume, transcript, essays, scholarship-specific materials.",
      aiPolicy: "unknown",
      sensitiveTags: ["race_ethnicity", "membership"],
      matchScore: 94,
      matchReasons: ["Engineering/computer science profile may fit after eligibility confirmation", "Graduate student category exists", "GPA and leadership are strong"],
      risks: ["Requires membership and GPA verification", "Sensitive identity confirmation required before applying"],
      nextAction: "Confirm membership/identity preference, submit GPA verification, then check open NSBE portal awards."
    },
    {
      id: "sbb-stem",
      name: "SBB Research Group Foundation STEM Scholarship",
      sponsor: "SBB Research Group Foundation",
      category: "STEM",
      url: "https://www.sbbscholarship.com/",
      applicationMethod: "online",
      contactEmail: "",
      amount: "$2,500",
      deadline: "quarterly",
      status: "verified",
      verifiedOn: "2026-06-03",
      eligibility: "Full-time student at a U.S. college pursuing a STEM degree with cumulative GPA of 3.5 or higher.",
      materials: "Online application and 500-word STEM impact essay.",
      aiPolicy: "restricted",
      sensitiveTags: [],
      matchScore: 93,
      matchReasons: ["Computer science/STEM fit", "GPA clears 3.5", "Interdisciplinary AI/data story fits essay"],
      risks: ["AI detection policy; final essay must be user-authored", "Quarter deadline must be confirmed in portal"],
      nextAction: "Use robot only for outline and fact organization; Kieron writes final essay in his own words."
    },
    {
      id: "gmis",
      name: "Great Minds in STEM Scholars Program",
      sponsor: "Great Minds in STEM",
      category: "STEM / Diversity",
      url: "https://www.gmis-scholars.org/",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Varies",
      deadline: "verify_current_cycle",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "STEM students; full details vary by sponsor award and year.",
      materials: "Online profile, resume, transcript, essays, recommendation or sponsor-specific materials.",
      aiPolicy: "unknown",
      sensitiveTags: ["race_ethnicity_possible"],
      matchScore: 89,
      matchReasons: ["STEM graduate profile", "Leadership/community story", "Diversity-oriented sponsor awards may fit after confirmation"],
      risks: ["Must verify current deadline and sponsor-specific eligibility"],
      nextAction: "Open portal and identify currently open awards for graduate CS/engineering students."
    },
    {
      id: "asme",
      name: "ASME Graduate Student Scholarships",
      sponsor: "American Society of Mechanical Engineers",
      category: "Engineering",
      url: "https://www.asme.org/asme-programs/students-and-faculty/scholarships/asme-scholarships-how-to-apply",
      applicationMethod: "online",
      contactEmail: "ASME.University@applyISTS.com",
      amount: "Varies",
      deadline: "2026-03-02",
      status: "monitor_next_cycle",
      verifiedOn: "2026-06-03",
      eligibility: "Graduate engineering scholarships primarily for mechanical engineering or mechanical engineering technology students.",
      materials: "ASME account, universal application, transcript, recommendations.",
      aiPolicy: "unknown",
      sensitiveTags: ["membership"],
      matchScore: 61,
      matchReasons: ["Engineering-related but not direct unless program qualifies", "Professional society opportunity"],
      risks: ["2026 deadline passed", "Mechanical engineering fit may be weak"],
      nextAction: "Monitor for 2027 cycle only if Engineering Management is accepted as related."
    },
    {
      id: "aes-engineering",
      name: "AES Engineering Scholarship",
      sponsor: "AES Engineering Solutions",
      category: "General / Engineering",
      url: "https://www.aesengineers.com/scholarships.php",
      applicationMethod: "email",
      contactEmail: "scholarships@aesengineers.com",
      amount: "$500",
      deadline: "2026-10-08",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "High school seniors and students attending a post-secondary educational facility; engineering major not required.",
      materials: "500-1000 word essay; include full name, current school, and plans for next year. Do not include resume unless requested.",
      aiPolicy: "prohibited",
      sensitiveTags: [],
      matchScore: 79,
      matchReasons: ["Open to post-secondary students", "Leadership/resilience prompt can fit", "Email-only simple application"],
      risks: ["Official page warns AI-generated applications will not be accepted", "2026 deadline comes from scholarship databases; official page may still show prior cycle until updated"],
      nextAction: "Verify 2026 official page, then Kieron writes final essay manually."
    },
    {
      id: "gem",
      name: "The GEM Fellowship",
      sponsor: "National GEM Consortium",
      category: "Graduate STEM Fellowship",
      url: "https://www.gemfellowship.org/",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Fellowship / tuition / stipend varies",
      deadline: "annual_fall",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "Underrepresented students pursuing MS or PhD in engineering or computer science; requires internships and GEM employer/university process.",
      materials: "Online application, essays, resume, transcript, recommendations.",
      aiPolicy: "unknown",
      sensitiveTags: ["race_ethnicity"],
      matchScore: 87,
      matchReasons: ["MS/CS and engineering management background", "Professional experience and leadership", "Strong GPA"],
      risks: ["Sensitive identity confirmation required", "Cycle/deadline must be verified", "May be more fellowship than one-off scholarship"],
      nextAction: "Verify whether current degree stage and university participation fit."
    },
    {
      id: "smart",
      name: "SMART Scholarship-for-Service",
      sponsor: "U.S. Department of Defense",
      category: "Federal STEM Fellowship",
      url: "https://www.smartscholarship.org/smart",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Tuition plus stipend if selected",
      deadline: "annual_late_fall",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "STEM students who meet citizenship, academic, and service-commitment requirements.",
      materials: "Online application, essays, transcript, references, service commitment review.",
      aiPolicy: "unknown",
      sensitiveTags: ["citizenship", "service_commitment"],
      matchScore: 83,
      matchReasons: ["Computer science and engineering management fit", "Public service/data background can help", "High-value funding"],
      risks: ["Service obligation", "Citizenship and field eligibility must be confirmed", "Not a quick application"],
      nextAction: "Review service commitment and eligible fields before drafting."
    },
    {
      id: "afcea-stem-major",
      name: "AFCEA STEM Major Scholarships",
      sponsor: "AFCEA Educational Foundation",
      category: "STEM / Cybersecurity",
      url: "https://www.afcea.org/education/scholarships",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Varies",
      deadline: "verify_current_cycle",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "STEM students, often including graduate students in cyber, computer science, IT, engineering, or related fields depending on award.",
      materials: "Online application, transcript, resume, essay, recommendations.",
      aiPolicy: "unknown",
      sensitiveTags: ["citizenship_possible"],
      matchScore: 82,
      matchReasons: ["CS, IT operations, cyber habits, and public-sector data experience", "Graduate GPA and technical work"],
      risks: ["Award-specific deadlines and citizenship requirements vary"],
      nextAction: "Filter AFCEA portal for graduate CS/cyber awards still open."
    },
    {
      id: "ieee-merwin",
      name: "Richard E. Merwin Student Scholarship",
      sponsor: "IEEE Computer Society",
      category: "Computer Science",
      url: "https://www.computer.org/volunteering/awards/scholarships/merwin",
      applicationMethod: "online",
      contactEmail: "",
      amount: "$1,000 and up",
      deadline: "annual_multiple",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "Active IEEE Computer Society student members in computer science/engineering or related fields with academic and leadership strength.",
      materials: "Membership, transcript, resume, volunteer/leadership evidence, essays.",
      aiPolicy: "unknown",
      sensitiveTags: ["membership"],
      matchScore: 80,
      matchReasons: ["Current CS path", "Leadership and service story", "Technical portfolio"],
      risks: ["Requires IEEE Computer Society membership", "Deadline must be verified"],
      nextAction: "Check current cycle and membership requirements."
    },
    {
      id: "last-mile",
      name: "Last Mile Education Fund",
      sponsor: "Last Mile Education Fund",
      category: "Technology / Need",
      url: "https://www.lastmile-ed.org/",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Varies",
      deadline: "rolling",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "Students pursuing tech/engineering pathways with financial need or emergency gaps; program types vary.",
      materials: "Online application, enrollment proof, financial gap details, transcript or documentation.",
      aiPolicy: "unknown",
      sensitiveTags: ["financial_need"],
      matchScore: 78,
      matchReasons: ["CS/technology pathway", "Financial resilience story may fit if user chooses", "Rolling-style funding may be faster"],
      risks: ["Financial details are sensitive", "Must avoid storing tax or bank data in app"],
      nextAction: "Confirm current program availability and only enter financial details manually in browser."
    },
    {
      id: "tmcf",
      name: "TMCF Scholarships Portal",
      sponsor: "Thurgood Marshall College Fund",
      category: "HBCU / Black Student",
      url: "https://www.tmcf.org/students-alumni/scholarships/",
      applicationMethod: "portal",
      contactEmail: "",
      amount: "Varies",
      deadline: "varies",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "Scholarships for students connected to publicly supported HBCUs and partner institutions; eligibility varies by award.",
      materials: "Portal profile, transcript, resume, essays, FAFSA or financial information if requested.",
      aiPolicy: "unknown",
      sensitiveTags: ["race_ethnicity", "hbcu", "financial_need_possible"],
      matchScore: 81,
      matchReasons: ["SUNO/HBCU background", "Leadership and GPA", "STEM and business-tech profile"],
      risks: ["Current school eligibility must be checked", "Sensitive identity/need confirmation required"],
      nextAction: "Create or review portal profile and filter for graduate/STEM awards."
    },
    {
      id: "uncf",
      name: "UNCF Scholarships Portal",
      sponsor: "UNCF",
      category: "HBCU / Black Student",
      url: "https://uncf.org/scholarships",
      applicationMethod: "portal",
      contactEmail: "",
      amount: "Varies",
      deadline: "varies",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "Many awards support Black students, HBCU students, STEM students, and students with financial need; award-specific rules vary.",
      materials: "Portal profile, transcript, resume, essays, financial need documents if requested.",
      aiPolicy: "unknown",
      sensitiveTags: ["race_ethnicity", "hbcu", "financial_need_possible"],
      matchScore: 79,
      matchReasons: ["SUNO/HBCU background", "Black student scholarships may fit after confirmation", "Strong service and academic record"],
      risks: ["Must filter for graduate awards", "Sensitive identity confirmation required"],
      nextAction: "Search portal for graduate, STEM, New Orleans/Louisiana, and HBCU awards."
    },
    {
      id: "hbcu-endowment-grad",
      name: "HBCU Endowment Fund Graduate School Scholarship",
      sponsor: "HBCU Endowment Fund",
      category: "HBCU / Graduate",
      url: "https://hbcuendowmentfund.org/scholarships/graduate",
      applicationMethod: "online",
      contactEmail: "scholarships@hbcuendowmentfund.org",
      amount: "Varies",
      deadline: "2026-04-01",
      status: "monitor_next_cycle",
      verifiedOn: "2026-06-03",
      eligibility: "Masters and doctoral students at HBCUs with strong academics, research, financial need, and service commitment.",
      materials: "Online application, research plan, personal statement, financial need information, recommendations.",
      aiPolicy: "unknown",
      sensitiveTags: ["hbcu", "financial_need"],
      matchScore: 76,
      matchReasons: ["HBCU/SUNO background", "3.5+ preferred GPA", "Service and leadership fit"],
      risks: ["2026 deadline passed", "Current graduate institution may not be HBCU"],
      nextAction: "Monitor 2027 cycle or use as essay model."
    },
    {
      id: "southern-foundation",
      name: "Southern University System Foundation Scholarships",
      sponsor: "Southern University System Foundation",
      category: "SUNO / Alumni",
      url: "https://foundation.sus.edu/",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Varies",
      deadline: "varies",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "Scholarships for Southern University System students; award-specific rules vary.",
      materials: "Foundation application, transcript, resume, essays, enrollment details.",
      aiPolicy: "unknown",
      sensitiveTags: ["hbcu", "financial_need_possible"],
      matchScore: 78,
      matchReasons: ["SUNO alumnus profile", "Campus leadership history", "Academic performance"],
      risks: ["May prioritize current Southern System students", "Current cycle must be found"],
      nextAction: "Search foundation scholarship portal for graduate or alumni continuing-education awards."
    },
    {
      id: "suno-scholarships",
      name: "SUNO Scholarships",
      sponsor: "Southern University at New Orleans",
      category: "SUNO / Alumni",
      url: "https://www.suno.edu/page/scholarships-home",
      applicationMethod: "internal",
      contactEmail: "",
      amount: "Varies",
      deadline: "varies",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "SUNO scholarship programs and awards; many are for current students and tied to credit hours.",
      materials: "SUNO scholarship application, transcript, enrollment information.",
      aiPolicy: "unknown",
      sensitiveTags: ["hbcu"],
      matchScore: 72,
      matchReasons: ["SUNO B.S. background", "Campus leadership", "Potential alumni/internal leads"],
      risks: ["May not fund current UNO graduate study", "Current student eligibility may not fit"],
      nextAction: "Ask SUNO financial aid/alumni office for alumni graduate scholarship leads."
    },
    {
      id: "cogic-charities",
      name: "COGIC Charities Scholarships",
      sponsor: "Church of God in Christ Charities",
      category: "Faith / Community Service",
      url: "https://www.cogic.org/cogiccharities/",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Varies",
      deadline: "verify_current_cycle",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "Faith/community scholarships; current instructions mention transcript upload and evaluation on leadership, community involvement, and academics.",
      materials: "Online application, transcript, essay, leadership/community service evidence.",
      aiPolicy: "unknown",
      sensitiveTags: ["religion"],
      matchScore: 75,
      matchReasons: ["Long-term community service", "Youth leadership experience", "Community leadership"],
      risks: ["Religious affiliation must be confirmed", "Current denomination/member eligibility must be verified"],
      nextAction: "Verify religious affiliation and membership eligibility privately before applying."
    },
    {
      id: "point-foundation",
      name: "Point Foundation Scholarships",
      sponsor: "Point Foundation",
      category: "Identity / Leadership",
      url: "https://pointfoundation.org/scholarships/",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Varies",
      deadline: "annual",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "LGBTQ+ students pursuing higher education; scholarship type varies.",
      materials: "Online application, essays, transcript, recommendations.",
      aiPolicy: "unknown",
      sensitiveTags: ["lgbtq"],
      matchScore: 30,
      matchReasons: ["Leadership and resilience may fit only if identity is confirmed"],
      risks: ["Sensitive identity not provided; do not apply without explicit user confirmation"],
      nextAction: "Exclude unless Kieron explicitly confirms eligibility."
    },
    {
      id: "shpe",
      name: "SHPE Scholarships",
      sponsor: "Society of Hispanic Professional Engineers",
      category: "STEM / Identity",
      url: "https://shpe.org/scholarships/",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Varies",
      deadline: "annual",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "Students pursuing STEM degrees who meet SHPE and award-specific requirements.",
      materials: "Online application, transcript, resume, essays.",
      aiPolicy: "unknown",
      sensitiveTags: ["race_ethnicity", "membership"],
      matchScore: 25,
      matchReasons: ["STEM fit only; identity/membership not confirmed"],
      risks: ["Sensitive identity not provided", "Likely not eligible unless confirmed"],
      nextAction: "Exclude unless eligibility is explicitly confirmed."
    },
    {
      id: "aises",
      name: "AISES Scholarships",
      sponsor: "American Indian Science and Engineering Society",
      category: "STEM / Identity",
      url: "https://www.aises.org/students/scholarships",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Varies",
      deadline: "annual",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "Indigenous students in STEM who meet tribal/community documentation and award-specific rules.",
      materials: "Online application, transcript, tribal/community documentation, essays.",
      aiPolicy: "unknown",
      sensitiveTags: ["race_ethnicity", "tribal_affiliation"],
      matchScore: 20,
      matchReasons: ["STEM fit only; identity not confirmed"],
      risks: ["Sensitive eligibility not provided; do not apply"],
      nextAction: "Exclude unless eligibility is explicitly confirmed."
    },
    {
      id: "lagrant-grad",
      name: "The LAGRANT Foundation Graduate Scholarship",
      sponsor: "The LAGRANT Foundation",
      category: "Communications / Diversity",
      url: "https://www.lagrantfoundation.org/scholarship-application-process",
      applicationMethod: "online",
      contactEmail: "tlfinfo@lagrant.com",
      amount: "$3,750 typical graduate award",
      deadline: "2026-02-27",
      status: "monitor_next_cycle",
      verifiedOn: "2026-06-03",
      eligibility: "Graduate/PhD students from underrepresented backgrounds in advertising, marketing, or public relations with GPA and full-time requirements.",
      materials: "Application, transcript, essay, personal statement, recommendation, resume.",
      aiPolicy: "unknown",
      sensitiveTags: ["race_ethnicity"],
      matchScore: 58,
      matchReasons: ["SUNO Observer/editorial experience", "Creative technologist and public-facing portfolio", "Diversity-oriented scholarship may fit after confirmation"],
      risks: ["2026 deadline passed", "Major must emphasize PR, marketing, or advertising"],
      nextAction: "Monitor 2027 only if program/field emphasis can be justified."
    },
    {
      id: "aace",
      name: "AACE International Scholarships",
      sponsor: "AACE International Education Board",
      category: "Engineering Management / Cost Engineering",
      url: "https://web.aacei.org/resources/career-mentoring-center/scholarships",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Varies",
      deadline: "annual",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "Students in engineering, construction management, cost engineering, project management, business, and related fields depending on award.",
      materials: "Online application, transcript, resume, recommendation, essay.",
      aiPolicy: "unknown",
      sensitiveTags: ["membership_possible"],
      matchScore: 74,
      matchReasons: ["Engineering management and operations fit", "Project/cost/data systems background", "Graduate leadership profile"],
      risks: ["Current deadline and degree eligibility must be verified"],
      nextAction: "Verify 2026-2027 application window and graduate eligibility."
    },
    {
      id: "agc-grad",
      name: "AGC Education and Research Foundation Graduate Scholarship",
      sponsor: "Associated General Contractors of America",
      category: "Construction / Engineering Management",
      url: "https://www.agc.org/learn/education-and-research-foundation/scholarship-program",
      applicationMethod: "online",
      contactEmail: "",
      amount: "$3,750 annual / up to $7,500 typical",
      deadline: "annual",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "Graduate students in construction management or construction engineering for the relevant academic term.",
      materials: "Online application, transcript, recommendations, construction/career statement.",
      aiPolicy: "unknown",
      sensitiveTags: [],
      matchScore: 65,
      matchReasons: ["Engineering management adjacent", "Operations and systems experience", "Leadership profile"],
      risks: ["Construction-specific fit must be proven"],
      nextAction: "Apply only if coursework/career goals can truthfully connect to construction management."
    },
    {
      id: "eesf",
      name: "Environmental Engineering and Science Foundation Scholarships",
      sponsor: "Environmental Engineering and Science Foundation",
      category: "Environmental Engineering",
      url: "https://www.eesfoundation.org/scholarship/",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Varies",
      deadline: "verify_current_cycle",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "Students accepted to or enrolled in accredited graduate programs in environmental engineering/science or related fields; diversity scholarships also exist.",
      materials: "Application, transcript, essays, recommendations.",
      aiPolicy: "unknown",
      sensitiveTags: ["race_ethnicity_possible"],
      matchScore: 56,
      matchReasons: ["Engineering graduate path", "Data systems can support environmental analytics if career goal fits"],
      risks: ["Program may not be environmental", "Sensitive sub-awards require confirmation"],
      nextAction: "Use only if coursework/research has an environmental systems angle."
    },
    {
      id: "dfi-grl",
      name: "DFI Educational Trust Goble Rausche Likins Scholarship",
      sponsor: "DFI Educational Trust",
      category: "Engineering / Computer Science",
      url: "https://trust.dfi.org/scholarships/goble-rausche-likins/",
      applicationMethod: "online",
      contactEmail: "",
      amount: "$5,000",
      deadline: "2026-05-15",
      status: "monitor_next_cycle",
      verifiedOn: "2026-06-03",
      eligibility: "Full-time undergraduate or graduate civil engineering, electrical engineering, or computer science students at accredited U.S. schools with civil-engineering application work experience.",
      materials: "Online application, official transcript, resume, recommendation, employment/internship evidence.",
      aiPolicy: "unknown",
      sensitiveTags: [],
      matchScore: 62,
      matchReasons: ["Computer science graduate fit", "Systems/data work could apply if civil-engineering context exists"],
      risks: ["2026 deadline passed", "Civil-engineering application experience may be missing"],
      nextAction: "Monitor next cycle only if civil infrastructure/data work can be documented."
    },
    {
      id: "aaae",
      name: "AAa/e Foundation Scholarship",
      sponsor: "Asian American Architects/Engineers Association Foundation",
      category: "Architecture / Engineering / Construction",
      url: "https://aaae.ngo/scholarship/apply-scholarship/",
      applicationMethod: "online",
      contactEmail: "apply@aaaesc.org",
      amount: "Varies",
      deadline: "2026-05-31",
      status: "monitor_next_cycle",
      verifiedOn: "2026-06-03",
      eligibility: "Full-time U.S. school students working toward architecture, engineering, planning, construction, or related professions; mandatory ceremony/video participation if awarded.",
      materials: "Resume, personal statement, sample work/project, transcript, recommendation.",
      aiPolicy: "unknown",
      sensitiveTags: ["race_ethnicity_possible"],
      matchScore: 47,
      matchReasons: ["Engineering adjacency", "Portfolio/project evidence"],
      risks: ["Deadline just passed", "Field fit and identity/association context may be weak"],
      nextAction: "Monitor next cycle only if construction/engineering project focus is relevant."
    },
    {
      id: "aee-foundation",
      name: "AEE Foundation Scholarship",
      sponsor: "Association of Energy Engineers Foundation",
      category: "Energy Management",
      url: "https://aeefoundation.org/scholarships/",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Varies",
      deadline: "annual",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "Students studying energy engineering, energy management, sustainable studies, or related fields.",
      materials: "Application, transcript, essay, recommendation, resume.",
      aiPolicy: "unknown",
      sensitiveTags: [],
      matchScore: 73,
      matchReasons: ["Engineering management plus systems/operations", "Portfolio mentions systems engineer energy", "Data dashboards and operational efficiency"],
      risks: ["Energy coursework/career intent must be verified"],
      nextAction: "Verify current deadline and connect career goal to energy/data management."
    },
    {
      id: "isa",
      name: "ISA Educational Foundation Scholarships",
      sponsor: "International Society of Automation",
      category: "Automation / Engineering",
      url: "https://www.isa.org/membership/students/scholarships",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Varies",
      deadline: "annual",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "Students in automation, instrumentation, systems, computer science, engineering, or related fields depending on award.",
      materials: "Application, transcript, resume, recommendation, essay.",
      aiPolicy: "unknown",
      sensitiveTags: ["membership_possible"],
      matchScore: 76,
      matchReasons: ["AI automation and workflow design", "Systems engineering and data automation", "CS/engineering management overlap"],
      risks: ["Current deadline and membership/section requirements vary"],
      nextAction: "Verify current cycle and local section eligibility."
    },
    {
      id: "sme-education",
      name: "SME Education Foundation Scholarships",
      sponsor: "SME Education Foundation",
      category: "Manufacturing / Engineering",
      url: "https://www.smeef.org/sme-education-foundation-scholarships/",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Varies",
      deadline: "annual",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "Students pursuing manufacturing engineering, technology, or closely related fields.",
      materials: "Online application, transcript, resume, essays, recommendations.",
      aiPolicy: "unknown",
      sensitiveTags: [],
      matchScore: 52,
      matchReasons: ["Engineering management and operations fit if manufacturing systems are a career goal"],
      risks: ["May not fit CS/EM without manufacturing angle"],
      nextAction: "Use only if career statement includes manufacturing systems/automation."
    },
    {
      id: "tau-beta-pi",
      name: "Tau Beta Pi Fellowships",
      sponsor: "Tau Beta Pi Engineering Honor Society",
      category: "Engineering Honor Society",
      url: "https://www.tbp.org/scholarships.cfm",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Varies",
      deadline: "annual",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "Tau Beta Pi members pursuing graduate study in engineering or related fields.",
      materials: "Membership, application, transcript, recommendations, essays.",
      aiPolicy: "unknown",
      sensitiveTags: ["membership"],
      matchScore: 50,
      matchReasons: ["Engineering graduate profile"],
      risks: ["Requires Tau Beta Pi membership; not confirmed"],
      nextAction: "Exclude unless membership is confirmed."
    },
    {
      id: "acm-sighpc",
      name: "ACM SIGHPC Computational and Data Science Fellowships",
      sponsor: "ACM SIGHPC",
      category: "Computer Science / Data",
      url: "https://www.sighpc.org/for-our-community/fellowships",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Fellowship varies",
      deadline: "annual",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "Graduate students pursuing computational and data science with diversity and inclusion goals depending on current cycle.",
      materials: "Research statement, transcript, references, CV/resume.",
      aiPolicy: "unknown",
      sensitiveTags: ["race_ethnicity_possible", "gender_possible"],
      matchScore: 70,
      matchReasons: ["CS/data systems focus", "Diversity and leadership story", "Research/career growth potential"],
      risks: ["May require research-intensive program", "Sensitive categories may apply"],
      nextAction: "Verify if current cycle is open and whether master's students qualify."
    },
    {
      id: "doe-csgf",
      name: "DOE Computational Science Graduate Fellowship",
      sponsor: "U.S. Department of Energy",
      category: "Federal STEM Fellowship",
      url: "https://www.krellinst.org/csgf/",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Full fellowship",
      deadline: "annual_winter",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "U.S. citizens or lawful permanent residents pursuing full-time PhD study in computational science fields.",
      materials: "Online application, essays, program of study, references, transcripts.",
      aiPolicy: "unknown",
      sensitiveTags: ["citizenship"],
      matchScore: 42,
      matchReasons: ["CS/data interest fit"],
      risks: ["Likely PhD-only and 2026 deadline passed", "May not fit current master's path"],
      nextAction: "Do not prioritize unless PhD plans are confirmed."
    },
    {
      id: "ndseg",
      name: "NDSEG Fellowship",
      sponsor: "Department of Defense",
      category: "Federal STEM Fellowship",
      url: "https://ndseg.sysplus.com/",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Full fellowship",
      deadline: "annual_fall",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "U.S. citizens/nationals pursuing doctoral degrees in supported science and engineering disciplines.",
      materials: "Online application, research statement, transcript, recommendations.",
      aiPolicy: "unknown",
      sensitiveTags: ["citizenship"],
      matchScore: 38,
      matchReasons: ["STEM/CS interest fit"],
      risks: ["Doctoral focus; current master's path likely not eligible"],
      nextAction: "Exclude unless doctoral study is planned."
    },
    {
      id: "nsf-grfp",
      name: "NSF Graduate Research Fellowship Program",
      sponsor: "National Science Foundation",
      category: "Federal STEM Fellowship",
      url: "https://www.nsfgrfp.org/",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Fellowship",
      deadline: "annual_fall",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "Early graduate students in eligible research-based STEM graduate programs; eligibility changes must be verified.",
      materials: "Research statement, personal statement, transcripts, recommendations.",
      aiPolicy: "unknown",
      sensitiveTags: ["citizenship"],
      matchScore: 40,
      matchReasons: ["CS/STEM profile and resilience story"],
      risks: ["May be ineligible if already holding/finishing a graduate degree", "Research-based degree requirement"],
      nextAction: "Do not apply until degree timeline is reconciled against NSF eligibility."
    },
    {
      id: "google-lime",
      name: "Google Lime Scholarship",
      sponsor: "Lime Connect and Google",
      category: "Computer Science / Disability",
      url: "https://www.limeconnect.com/programs/page/google-lime-scholarship",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Varies",
      deadline: "annual",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "Computer science or related students with disabilities who meet academic and enrollment criteria.",
      materials: "Online application, resume, transcript, essays.",
      aiPolicy: "unknown",
      sensitiveTags: ["disability"],
      matchScore: 26,
      matchReasons: ["CS fit only; disability eligibility not provided"],
      risks: ["Sensitive eligibility not provided; do not apply without explicit confirmation"],
      nextAction: "Exclude unless Kieron explicitly confirms eligibility."
    },
    {
      id: "nabj",
      name: "NABJ Scholarships",
      sponsor: "National Association of Black Journalists",
      category: "Journalism / Black Student",
      url: "https://nabjonline.org/student-services/scholarships/",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Varies",
      deadline: "annual",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "Student journalists and media students; eligibility varies by award.",
      materials: "Application, transcript, resume, work samples, essays, recommendations.",
      aiPolicy: "unknown",
      sensitiveTags: ["race_ethnicity", "membership_possible"],
      matchScore: 66,
      matchReasons: ["Editor-in-Chief of The SUNO Observer", "Digital publishing and audience analytics", "Black student/media profile may fit after confirmation"],
      risks: ["Current field is CS/engineering, not journalism", "Sensitive identity and membership may be required"],
      nextAction: "Use only for awards accepting multidisciplinary media/technology students."
    },
    {
      id: "spj-foundation",
      name: "SPJ Foundation Scholarships",
      sponsor: "Society of Professional Journalists Foundation",
      category: "Journalism",
      url: "https://www.spj.org/a-scholarships.asp",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Varies",
      deadline: "annual",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "Journalism students and student journalists; award-specific rules vary.",
      materials: "Application, transcript, resume, clips/work samples, essays.",
      aiPolicy: "unknown",
      sensitiveTags: [],
      matchScore: 55,
      matchReasons: ["SUNO Observer leadership", "Digital publishing experience"],
      risks: ["May require journalism major or career intent"],
      nextAction: "Use only if award accepts media leadership outside journalism major."
    },
    {
      id: "project-yellow-light",
      name: "Project Yellow Light Video Scholarship",
      sponsor: "Project Yellow Light",
      category: "Creative / Film",
      url: "https://projectyellowlight.com/",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Varies",
      deadline: "annual_spring",
      status: "monitor_next_cycle",
      verifiedOn: "2026-06-03",
      eligibility: "Students create a video, billboard, or radio PSA to discourage distracted driving.",
      materials: "Original creative submission, student verification, online form.",
      aiPolicy: "unknown",
      sensitiveTags: [],
      matchScore: 68,
      matchReasons: ["Filmmaking portfolio", "Short-form video experience", "Public-service message fit"],
      risks: ["Spring deadline may have passed", "Creative work must be original"],
      nextAction: "Monitor next cycle and prepare original film concept."
    },
    {
      id: "frame-my-future",
      name: "Frame My Future Scholarship Contest",
      sponsor: "Church Hill Classics",
      category: "Creative / General",
      url: "https://www.diplomaframe.com/contests/frame-my-future-scholarship.aspx",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Varies",
      deadline: "annual",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "Students submit creative work showing future goals; rules vary by current contest.",
      materials: "Creative entry, short description, student details.",
      aiPolicy: "unknown",
      sensitiveTags: [],
      matchScore: 59,
      matchReasons: ["Creative technologist brand", "Film/game/portfolio assets", "Career-goal story"],
      risks: ["Must verify current cycle and AI/media rules"],
      nextAction: "Use only if open and original creative entry is allowed."
    },
    {
      id: "new-orleans-film-society",
      name: "New Orleans Film Society Artist Opportunities",
      sponsor: "New Orleans Film Society",
      category: "Film / Local",
      url: "https://neworleansfilmsociety.org/",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Varies",
      deadline: "varies",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "Local filmmaker opportunities, labs, grants, and festival programs vary by year.",
      materials: "Film links, artist statement, project description, resume/bio.",
      aiPolicy: "unknown",
      sensitiveTags: [],
      matchScore: 72,
      matchReasons: ["New Orleans filmmaker", "Black NOLA Film Fest context", "Public YouTube film work"],
      risks: ["May be artistic grant rather than tuition scholarship", "Program-specific eligibility varies"],
      nextAction: "Search current artist support and student filmmaker opportunities."
    },
    {
      id: "berkeley-film-foundation",
      name: "Berkeley Film Foundation Student Grants",
      sponsor: "Berkeley Film Foundation",
      category: "Film / Student Grant",
      url: "https://berkeleyfilmfoundation.org/student-grants",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Up to $5,000",
      deadline: "2026-04-13",
      status: "not_eligible",
      verifiedOn: "2026-06-03",
      eligibility: "Full-time film-program students with required clip/trailer and community screening obligations.",
      materials: "Submittable application, clip/trailer up to 10 minutes, project details.",
      aiPolicy: "unknown",
      sensitiveTags: [],
      matchScore: 34,
      matchReasons: ["Filmmaking fit"],
      risks: ["Deadline passed and requires full-time film program", "Not a fit for CS/Engineering Management unless film program enrollment exists"],
      nextAction: "Do not apply under current profile."
    },
    {
      id: "bafta-us",
      name: "BAFTA US Scholarships",
      sponsor: "BAFTA North America",
      category: "Film / Graduate",
      url: "https://www.bafta.org/programmes/us-scholarships/",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Varies",
      deadline: "2026-06-26",
      status: "not_eligible",
      verifiedOn: "2026-06-03",
      eligibility: "Graduate students studying filmmaking or related degree at New York or appropriate institute for named scholarships.",
      materials: "Online application, creative work, financial and program information.",
      aiPolicy: "unknown",
      sensitiveTags: ["financial_need_possible"],
      matchScore: 36,
      matchReasons: ["Film portfolio fit"],
      risks: ["Current degree is not filmmaking and location/program likely not eligible"],
      nextAction: "Do not apply unless enrolled in an eligible film-related graduate program."
    },
    {
      id: "issaef-2026",
      name: "ISSAEF Graduate Cybersecurity Scholarships",
      sponsor: "ISSA Education Foundation",
      category: "Cybersecurity / Graduate",
      url: "https://issaef.org/wp-content/uploads/2026/02/2026_ISSAEF_AppForm_General-Final2.pdf",
      applicationMethod: "online",
      contactEmail: "",
      amount: "$2,000-$3,500",
      deadline: "2026-06-15",
      status: "verified",
      verifiedOn: "2026-06-10",
      newThisRun: true,
      manualOnly: true,
      eligibility: "Full-time graduate student in an information-security-related program, pursuing a cybersecurity career, with a 3.0+ graduate GPA. ISSA membership is not required.",
      materials: "Official application PDF, unofficial transcript, personal statement, security coursework/work history, community service, extracurriculars, and at least one recommendation letter.",
      aiPolicy: "unknown",
      sensitiveTags: [],
      matchScore: 94,
      matchReasons: ["Graduate computer science, IT operations, cloud/data, identity and permission management fit", "Strong graduate academic record and community service exceed stated thresholds"],
      risks: ["Cybersecurity career intent must be clear", "At least one recommendation is required", "AI policy is not stated"],
      nextAction: "Open the official application PDF, complete it manually, and request a cybersecurity or faculty recommendation immediately."
    },
    {
      id: "omega-community-growth-2026",
      name: "Omega Law Community Growth Scholarship",
      sponsor: "Omega Law Group",
      category: "Community Service / Leadership",
      url: "https://www.omegalaw.com/scholarship/",
      applicationMethod: "online",
      contactEmail: "",
      amount: "$2,500",
      deadline: "2026-06-15",
      status: "verified",
      verifiedOn: "2026-06-10",
      newThisRun: true,
      manualOnly: true,
      eligibility: "U.S. resident age 18 or older, in good academic standing, with proof of enrollment or acceptance at an accredited U.S. undergraduate or graduate school.",
      materials: "Online form, proof of enrollment, student and financial-aid-office information, plus an original essay under 1,000 words or a 1-2 minute unlisted YouTube video.",
      aiPolicy: "restricted",
      sensitiveTags: ["residency"],
      matchScore: 93,
      matchReasons: ["Long-term community service directly fits the prompt", "Filmmaking background makes the optional video response unusually strong"],
      risks: ["Original applicant-authored work is required", "Application asks for student ID and financial aid office details; enter these manually"],
      nextAction: "Use an original video response centered on community leadership, with Kieron scripting and recording the final submission."
    },
    {
      id: "iitsec-postgraduate-2026",
      name: "I/ITSEC Postgraduate Scholarship",
      sponsor: "National Training and Simulation Association",
      category: "Computer Science / Simulation",
      url: "https://www.xcdsystem.com/iitsec/forms/index.cfm?ID=7pa5WgB",
      applicationMethod: "online",
      contactEmail: "",
      amount: "Varies",
      deadline: "2026-06-21",
      status: "verified",
      verifiedOn: "2026-06-10",
      newThisRun: true,
      manualOnly: true,
      eligibility: "Documented U.S. citizen enrolled full-time in a master's or doctoral program related to modeling, simulation, training, or education; computer science and information sciences are listed eligible fields.",
      materials: "Online application, 500-word career statement, proof of citizenship, resume, undergraduate and graduate transcripts, and at least one professor recommendation.",
      aiPolicy: "unknown",
      sensitiveTags: ["citizenship"],
      matchScore: 91,
      matchReasons: ["MS Computer Science and game/film systems work can support modeling and simulation goals", "Technical leadership and creative production offer a distinctive application angle"],
      risks: ["Citizenship must be confirmed", "Recommendation and citizenship documentation are required", "Award includes conference and future paper responsibilities"],
      nextAction: "Confirm U.S. citizenship and modeling/simulation career intent before starting the official application."
    },
    {
      id: "la-tutors-innovation-2026",
      name: "Innovation in Education Scholarship",
      sponsor: "LA Tutors 123",
      category: "Technology / Innovation",
      url: "https://www.latutors123.com/scholarships/innovation-in-education/",
      applicationMethod: "online",
      contactEmail: "",
      amount: "$500",
      deadline: "2026-06-20",
      status: "verified",
      verifiedOn: "2026-06-10",
      newThisRun: true,
      manualOnly: true,
      eligibility: "Current graduate student with a cumulative GPA of at least 3.0 who meets the listed U.S./Canada citizenship, residency, or student-status requirement and created an innovative project that helps others.",
      materials: "Online form, original project essay, project link or evidence, recommendation letter, and a project photo.",
      aiPolicy: "prohibited",
      sensitiveTags: ["citizenship_or_student_status"],
      matchScore: 95,
      matchReasons: ["Scholarship robot, automation work, portfolio, and technical projects directly match the innovation criterion", "Strong academic record and service-oriented technology story are compelling"],
      risks: ["Final essay must be entirely applicant-authored", "Recommendation and project photo are required"],
      nextAction: "Choose the scholarship robot or another documented project, gather a recommendation and project photo, then write the final essay without AI-generated prose."
    },
    {
      id: "morewithus-fall-2026",
      name: "MoreWithUs Fall 2026 Scholarship",
      sponsor: "MoreWithUs - Everyday Jobs",
      category: "Work / Volunteer Experience",
      url: "https://morewithus.com/pages/scholarship",
      applicationMethod: "email",
      contactEmail: "team@morewithus.com",
      amount: "$500",
      deadline: "2026-06-30",
      status: "verified",
      verifiedOn: "2026-06-10",
      newThisRun: true,
      manualOnly: true,
      eligibility: "Currently enrolled high school, vocational school, or college student. The sponsor requires a free MoreWithUs profile.",
      materials: "Free profile and either a one-page essay or an approximately two-minute video about a work or volunteer experience.",
      aiPolicy: "unknown",
      sensitiveTags: ["platform_profile"],
      matchScore: 92,
      matchReasons: ["Hotel, nonprofit, city government, and church service experience fit the prompt directly", "Video option fits Kieron's filmmaking background"],
      risks: ["Requires a platform profile", "Winner's essay or video may be posted publicly", "AI policy is not stated"],
      nextAction: "Create the free profile manually and submit an original video or essay using the official instructions."
    },
    {
      id: "fasig-brooks-comeback-2026",
      name: "Come Back Stronger Scholarship",
      sponsor: "Fasig | Brooks Law Offices",
      category: "Resilience / General",
      url: "https://fasigbrooks.com/scholarships/come-back-stronger-scholarship/",
      applicationMethod: "online",
      contactEmail: "",
      amount: "$1,000",
      deadline: "2026-07-15",
      status: "verified",
      verifiedOn: "2026-06-10",
      newThisRun: true,
      manualOnly: true,
      eligibility: "U.S. legal resident currently enrolled in a vocational or two- to four-year post-secondary institution, including graduate students, with at least a 3.0 GPA.",
      materials: "Online form, original 750-1,000 word essay, professional resume, and current transcript.",
      aiPolicy: "prohibited",
      sensitiveTags: ["residency"],
      matchScore: 97,
      matchReasons: ["The prompt directly fits perseverance through family responsibilities, financial pressure, work, and college", "Resume and strong academic record provide compelling supporting evidence"],
      risks: ["AI-generated writing is expressly disallowed", "Florida applicants receive preference"],
      nextAction: "Kieron writes the final essay personally; use the robot only to organize verified dates and supporting facts."
    },
    {
      id: "gutsy-grad-2026",
      name: "Gutsy Graduate Student Essay Scholarship",
      sponsor: "Scholarships360",
      category: "Graduate / General",
      url: "https://scholarships360.org/scholarships/search/gutsy-graduate-student-essay-scholarship/",
      applicationMethod: "portal",
      contactEmail: "",
      amount: "$1,000",
      deadline: "2026-06-30",
      status: "verified",
      verifiedOn: "2026-06-10",
      newThisRun: true,
      manualOnly: true,
      eligibility: "Current graduate students or college seniors entering graduate school who are U.S. citizens or permanent residents.",
      materials: "Free Scholarships360 account and a maximum 250-word essay about funding graduate education and why the award would help.",
      aiPolicy: "unknown",
      sensitiveTags: ["citizenship", "platform_profile"],
      matchScore: 90,
      matchReasons: ["Current MS Computer Science enrollment is a direct fit", "Self-funded education and active scholarship search align closely with the prompt"],
      risks: ["Requires an account", "Sponsor gives higher consideration to active platform users", "Citizenship or permanent residency must be confirmed"],
      nextAction: "Create the account manually, confirm residency eligibility, and submit an original concise essay."
    },
    {
      id: "gen-kelly-tanabe-2026",
      name: "Gen and Kelly Tanabe Scholarship",
      sponsor: "Gen and Kelly Tanabe",
      category: "Graduate / Merit",
      url: "https://www.genkellyscholarship.com/apply",
      applicationMethod: "online",
      contactEmail: "",
      amount: "$1,000",
      deadline: "open_current_cycle",
      status: "verified",
      verifiedOn: "2026-06-10",
      newThisRun: true,
      manualOnly: true,
      eligibility: "Legal U.S. resident who is currently a college or graduate student, including adult students.",
      materials: "Online application and personal statement; the selection committee states that the personal statement is the primary factor.",
      aiPolicy: "unknown",
      sensitiveTags: ["residency"],
      matchScore: 88,
      matchReasons: ["Graduate student and adult-student eligibility are explicit", "Academic merit, leadership, and resilience provide multiple statement angles"],
      risks: ["The current deadline is shown inside the live application rather than on the public details page", "Residency must be confirmed", "AI policy is not stated"],
      nextAction: "Open the live application, confirm its displayed closing date, and write the personal statement in Kieron's own voice."
    },
    {
      id: "schaffer-ssd-advocacy-2026",
      name: "Social Security Disability Advocacy Scholarship",
      sponsor: "Schaffer & Associates",
      category: "Technology / Social Impact",
      url: "https://www.schafferlawyers.com/2026-social-security-disability-advocacy-scholarship/",
      applicationMethod: "online",
      contactEmail: "",
      amount: "$1,000",
      deadline: "2026-08-31",
      status: "verified",
      verifiedOn: "2026-06-10",
      newThisRun: true,
      manualOnly: true,
      eligibility: "U.S. legal resident enrolled for Fall 2026 in a post-secondary institution, including graduate school, with at least a 3.0 GPA.",
      materials: "Online form, applicant-authored 750-1,000 word policy essay, professional resume, and transcript.",
      aiPolicy: "prohibited",
      sensitiveTags: ["residency"],
      matchScore: 86,
      matchReasons: ["Public-sector data and systems experience can support an accessibility and efficiency proposal", "Technical background fits a thoughtful modernization argument"],
      risks: ["AI-generated content is expressly disallowed", "Ohio applicants receive preference", "The essay requires independent policy research"],
      nextAction: "Research SSD accessibility problems from authoritative sources and write the final policy essay manually."
    },
    {
      id: "college-is-power-2026",
      name: "College Is Power Scholarship",
      sponsor: "College Is Power",
      category: "Graduate / Career Goals",
      url: "https://www.collegeispower.com/scholarship.cfm",
      applicationMethod: "online",
      contactEmail: "",
      amount: "$1,000",
      deadline: "2026-08-31",
      status: "verified",
      verifiedOn: "2026-06-10",
      newThisRun: true,
      manualOnly: true,
      eligibility: "U.S. citizen or permanent resident age 17 or older who is currently enrolled in higher education or plans to enroll within 12 months; graduate students are explicitly listed.",
      materials: "Online application and a statement of 150 words or fewer about the primary goal for attending school.",
      aiPolicy: "unknown",
      sensitiveTags: ["citizenship"],
      matchScore: 85,
      matchReasons: ["Graduate school and Computers/IT/Technology are explicit application options", "Clear technical leadership goal fits the short response"],
      risks: ["Citizenship or permanent residency must be confirmed", "Application collects demographic and contact information", "AI policy is not stated"],
      nextAction: "Review the privacy terms, confirm citizenship eligibility, and complete the short response personally."
    },
    {
      id: "fastweb-source",
      name: "Fastweb Scholarship Search",
      sponsor: "Fastweb",
      category: "Search Source",
      url: "https://www.fastweb.com/college-scholarships",
      applicationMethod: "search",
      contactEmail: "",
      amount: "Varies",
      deadline: "varies",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "Scholarship database; not itself a scholarship.",
      materials: "Use only to discover official sponsor pages.",
      aiPolicy: "not_applicable",
      sensitiveTags: [],
      matchScore: 45,
      matchReasons: ["Can discover additional graduate scholarships"],
      risks: ["Must verify every result on official sponsor site", "Do not apply through sketchy redirects"],
      nextAction: "Use as secondary search source after official/internal sources."
    },
    {
      id: "careeronestop",
      name: "CareerOneStop Scholarship Finder",
      sponsor: "U.S. Department of Labor / CareerOneStop",
      category: "Search Source",
      url: "https://www.careeronestop.org/Toolkit/Training/find-scholarships.aspx",
      applicationMethod: "search",
      contactEmail: "",
      amount: "Varies",
      deadline: "varies",
      status: "verified",
      verifiedOn: "2026-06-03",
      eligibility: "Federal-sponsored searchable database of scholarships, fellowships, grants, and other aid opportunities.",
      materials: "Use filters for graduate degree, U.S. study, engineering, computer science, Louisiana, Black/African American, faith/service, and creative fields.",
      aiPolicy: "not_applicable",
      sensitiveTags: [],
      matchScore: 77,
      matchReasons: ["Legitimacy-oriented search source", "Useful for reaching 300 prospects", "Recommended-style database source"],
      risks: ["Every listing still requires current sponsor verification"],
      nextAction: "Run filtered searches and import official sponsor links."
    },
    {
      id: "bold-org-source",
      name: "Bold.org Scholarship Search",
      sponsor: "Bold.org",
      category: "Search Source",
      url: "https://bold.org/scholarships/",
      applicationMethod: "portal",
      contactEmail: "",
      amount: "Varies",
      deadline: "varies",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "Scholarship platform; individual award eligibility varies.",
      materials: "Portal profile and scholarship-specific essays.",
      aiPolicy: "unknown",
      sensitiveTags: ["platform_profile"],
      matchScore: 44,
      matchReasons: ["Can fill broad prospect count", "May include niche graduate/STEM/film awards"],
      risks: ["Quality varies; avoid low-signal no-essay leads that only harvest data"],
      nextAction: "Use only for high-fit, essay-based awards with clear sponsor and no fees."
    },
    {
      id: "scholarshipamerica",
      name: "Scholarship America Hub",
      sponsor: "Scholarship America",
      category: "Search Source",
      url: "https://scholarshipamerica.org/students/browse-scholarships/",
      applicationMethod: "portal",
      contactEmail: "",
      amount: "Varies",
      deadline: "varies",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "Scholarship America-administered awards; individual eligibility varies.",
      materials: "Portal profile, essays, transcript, financial need documents if required.",
      aiPolicy: "unknown",
      sensitiveTags: ["financial_need_possible"],
      matchScore: 54,
      matchReasons: ["Legitimate administrator", "Good for national scholarship discovery"],
      risks: ["Must filter for graduate and current open awards"],
      nextAction: "Search for STEM, technology, Louisiana, and graduate awards."
    },
    {
      id: "college-board-bigfuture",
      name: "College Board BigFuture Scholarship Search",
      sponsor: "College Board BigFuture",
      category: "Search Source",
      url: "https://bigfuture.collegeboard.org/scholarship-search",
      applicationMethod: "search",
      contactEmail: "",
      amount: "Varies",
      deadline: "varies",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "Scholarship search tool; individual awards vary.",
      materials: "Use to discover official sponsor pages.",
      aiPolicy: "not_applicable",
      sensitiveTags: [],
      matchScore: 48,
      matchReasons: ["Useful for checking deadlines and degree-level filters"],
      risks: ["Some listed opportunities may be undergrad only"],
      nextAction: "Use only as lead source; verify on official sponsor site."
    },
    {
      id: "scholarships-com",
      name: "Scholarships.com Search",
      sponsor: "Scholarships.com",
      category: "Search Source",
      url: "https://www.scholarships.com/",
      applicationMethod: "search",
      contactEmail: "",
      amount: "Varies",
      deadline: "varies",
      status: "prospect",
      verifiedOn: "2026-06-03",
      eligibility: "Scholarship search platform; individual awards vary.",
      materials: "Use to discover official sponsor pages, not as final source of truth.",
      aiPolicy: "not_applicable",
      sensitiveTags: ["platform_profile"],
      matchScore: 42,
      matchReasons: ["Can help expand prospect pool"],
      risks: ["Avoid spammy offers, fees, and excessive data collection"],
      nextAction: "Use after official sources and CareerOneStop."
    }
  ]
};
